name: Skyarc
favicon: null
layout_spectrum: 0.0002824708353728056
typography_spectrum: 0.08245554147288203
title: SkyArc Imaging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45165759650990367
  lightness: 0.1801867000758648
  saturation: 0.6935974878724664
  rhythmicContrast: 0.4458368301857263
purpose: []
